[package]
name = "aries"
version = "0.1.0"
authors = ["k-michikawa"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
diesel = { version = "1.4.5", features = ["postgres"] }
dotenv = "0.15.0"
