version: "3.8"

services:
  db:
    image: postgres:13
    container_name: aries_db
    volumes:
      # - ./db/initdb:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: aries_db
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
  web:
    container_name: aries_web
    build:
      context: .
      target: "development"
    ports:
      - "9000:9000"
    environment:
      RUST_BACKTRACE: 1
      LISTEN_ADDRESS: "[::]:9000"
      DATABASE_URL: postgres://aries:aries@db:5432/aries_db
    volumes:
      - .:/app
      - cargo_cache:/usr/local/cargo/registry
      - target_cache:/app/target
    command: /bin/sh -c "cargo watch -x run"

volumes:
  db_data:
  cargo_cache:
  target_cache:
