version: "3.8"

services:
  aries-db:
    image: postgres:13
    container_name: aries-db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: aries-db
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    # 実行したSQLを標準出力に吐きたい場合
    command: postgres -c log_destination=stderr -c log_statement=all -c log_connections=on -c log_disconnections=on
  grpc:
    depends_on:
      - aries-db
    container_name: aries
    build:
      context: .
      target: "development"
    ports:
      - "9000:9000"
    environment:
      RUST_BACKTRACE: 1
      LISTEN_ADDRESS: "[::]:9000"
      DATABASE_URL: postgres://aries:aries@aries-db:5432/aries-db
    volumes:
      - .:/app
      - cargo_cache:/usr/local/cargo/registry
      - target_cache:/app/target
    command: /bin/sh -c "cargo watch -x run"

volumes:
  db_data:
  cargo_cache:
  target_cache:
